version: '3'
services:
  app:
    container_name: app_0
    image: mrusna4/cs441-course-project:docker-test
    ports:
      - '8080:8080'
      - '2551:2551'
    hostname: artery
    environment:
      CLUSTER_PORT: 2551
      CLUSTER_IP: app
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: "${TYPE}_SIMULATION"
    depends_on:
      - seed
  seed:
    container_name: node_0
    image: mrusna4/cs441-course-project:docker-test
    ports:
      - '1600:1600'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: "${TYPE}_NODE"
      NODE_ID: 0
  c1:
    container_name: node_1
    image: mrusna4/cs441-course-project:docker-test
    ports:
      - '1601:1601'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: c1
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: "${TYPE}_NODE"
      NODE_ID: 1
    depends_on:
      - seed
      - app
  c2:
    container_name: node_2
    image: mrusna4/cs441-course-project:docker-test
    ports:
      - '1602:1602'
    environment:
      CLUSTER_PORT: 1602
      CLUSTER_IP: c2
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: "${TYPE}_NODE"
      NODE_ID: 2
    depends_on:
      - seed
      - app

