version: '3'
services:
  app:
    image: course-project
    ports:
      - '8080:8080'
      - '2551:2551'
    hostname: artery
    environment:
      CLUSTER_PORT: 2551
      CLUSTER_IP: app
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: CAN_SIMULATION
    depends_on:
      - seed
  seed:
    container_name: node_1
    image: course-project
    ports:
      - '1600:1600'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: CAN_NODE
      NODE_ID: 0
  c1:
    image: course-project
    ports:
      - '1601:1601'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: c1
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: CAN_NODE
      NODE_ID: 2
    depends_on:
      - seed
      - app
  c2:
    image: course-project
    ports:
      - '1602:1602'
    environment:
      CLUSTER_PORT: 1602
      CLUSTER_IP: c2
      SEED_PORT_1600_TCP_ADDR: seed
      MODE: CAN_NODE
      NODE_ID: 4
    depends_on:
      - seed
      - app

